### ISSUE TITLE
Release 生成時のメモ

### ISSUE THREAD

**Issue by toshi0806** [smkwlab/sotsuron-template#16]
Release 生成時に自動で生成される1行コメント的なやつがイマイチ。

どこかの commit メッセージが使われてるっぽいんだけど、なんとかしたい。

**Comment by tsuyopon123** [comment]
tagが打たれたcommitのメッセージっぽいですね

Release Noteの中身が空欄のときに表示されるようです

**Comment by tsuyopon123** [comment]
https://github.com/softprops/action-gh-release#-customizing

`body` か `generate_release_notes` を使うのが良さそうな気がします
